[package]
name = "projeto_tcc"
version = "0.1.0"
edition = "2024"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[dependencies]
avian3d = "0.3.0"
bevy = "0.16.1"
rand = "0.9.1"
rust_decimal = "1.37.1"
